parameters:
#    o_auth.example.class: LogbookREST\OAuthBundle\Example

services:
#    o_auth.example:
#        class: %o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
