imports:
    - { resource: config.yml }

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        storage_id: session.storage.mock_file
    csrf_protection:
        enabled:    false    

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/test.db #:memory:
        memory: true
        charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        
assetic:
    use_controller: true