frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /security

task:
    resource: "@TaskBundle/Resources/config/routing.yml"
    prefix:   /security

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /security
    
users_normal:
    resource: "@UserBundle/Resources/config/routing/api_users.yml"
    prefix:   /users
    
sprint_normal:
    resource: "@SprintBundle/Resources/config/routing/sprint.yml"
    prefix:   /sprint
   
task_normal:
    resource: "@TaskBundle/Resources/config/routing/task.yml"
    prefix:   /task
    
messages_normal:
    resource: "@MessageBundle/Resources/config/routing/message.yml"
    prefix:   /message    
    
urgencies_normal:
    resource: "@TaskBundle/Resources/config/routing/urgency.yml"
    prefix:   /urgency
    
project_normal:
    resource: "@ProjectBundle/Resources/config/routing/project.yml"
    prefix:   /project     
    
sprint:
    resource: "@SprintBundle/Resources/config/routing.yml"
    prefix:   /security

synchonize:
    resource: "@SynchronizeBundle/Resources/config/routing.yml"
    prefix:   /security   
    
o_auth:
    resource: "@OAuthBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

login:
    pattern: /login
    defaults: { _controller: FrontendBundle:Frontend:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout