entry:
    resource: "@EntryBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
log:
    resource: "@LogBundle/Resources/config/routing.yml"
    prefix:   /    
    
image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /
    
o_auth:
    resource: "@OAuthBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc