projects_list:
    pattern: /
    defaults: { _controller: ProjectBundle:Project:listProjects }
    
show_normal_project:
    pattern: /see/{id}
    defaults: { _controller: ProjectBundle:Project:projectShow }
    
project_creation:
    pattern: /create
    defaults: { _controller: ProjectBundle:Project:newProject }
    
project_edit:
    pattern: /edit/{id}
    defaults: { _controller: ProjectBundle:Project:editProject }
    
delete_normal_project:
    pattern: /delete/{id}
    defaults: { _controller: ProjectBundle:Project:deleteProject }
    
create_backlog:
    pattern: /backlog-task/create/{id}
    defaults: { _controller: ProjectBundle:Project:newBacklog }
    
edit_backlog:
    pattern: /backlog-task/edit/{id}
    defaults: { _controller: ProjectBundle:Project:editBacklog }
    
delete_backlog:
    pattern: /backlog-task/delete/{id}
    defaults: { _controller: ProjectBundle:Project:deleteBacklog }

finalize_backlog:
    pattern: /backlog-task/finalize/{id}
    defaults: { _controller: ProjectBundle:Project:finalizeBacklog }
    
create_issue:
    pattern: /issue/create/{id}
    defaults: { _controller: ProjectBundle:Project:newIssue }
    
edit_issue:
    pattern: /issue/edit/{id}
    defaults: { _controller: ProjectBundle:Project:editIssue }
    
finalize_issue:
    pattern: /issue/finalize/{id}
    defaults: { _controller: ProjectBundle:Project:finalizeIssue }

planning_poker:
    pattern: /planning-poker/{id}
    defaults: { _controller: ProjectBundle:Project:planningPoker }

set_story_points:
    pattern: /set-story-points/{id}
    defaults: { _controller: ProjectBundle:Project:setPointsStory }