parameters:
    entry.handler.class: LogbookREST\EntryBundle\Handler\EntryHandler
    tag.handler.class: LogbookREST\EntryBundle\Handler\TagHandler
services:
    entry.handler:
        class: %entry.handler.class%
        arguments: [@doctrine.orm.entity_manager, @form.factory]   

    tag.handler:
          class: %tag.handler.class%
          arguments: [@doctrine.orm.entity_manager, @form.factory]