parameters:
    user.handler.class: LogbookREST\UserBundle\Handler\UserHandler
    api.user.handler.class: LogbookREST\UserBundle\Handler\ApiUserHandler
    user.create_salt.class: LogbookREST\UserBundle\EventListener\CreateUserSaltEventSubscriber
    user.class: LogbookREST\UserBundle\Entity\User
    user.provider.class: LogbookREST\UserBundle\Provider\UserProvider
    user.repository.class: LogbookREST\UserBundle\Entity\UserRepository
    

services:
    user.handler:
        class: %user.handler.class%
        arguments: [@doctrine.orm.entity_manager, @form.factory, @security.encoder_factory]
    api.user.handler:
        class: %api.user.handler.class%
        arguments: [@doctrine.orm.entity_manager, @form.factory, @security.encoder_factory]    
    user.create_salt_listener:
        class: %user.create_salt.class%
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_subscriber }
    user.manager:
        class:            Doctrine\ORM\EntityManager
        factory_service:  doctrine
        factory_method:   getManagerForClass
        arguments: [%user.class%]        
    user.repository:
        class: %user.repository.class% 
        factory_service: user.manager
        factory_method: getRepository
        arguments: [%user.class%]
    user.provider:
        class: %user.provider.class%
        arguments: [@user.repository]