api_users_list:
    pattern: /
    defaults: { _controller: UserBundle:UserNormal:listApiUsers }
    
show_normal_api_user:
    pattern: /api_user/{id}
    defaults: { _controller: UserBundle:UserNormal:apiUserShow }  
    
edit_profile:
    pattern: /profile
    defaults: { _controller: UserBundle:UserNormal:editProfile }    
    
new_normal_api_user:
    pattern: /new
    defaults: { _controller: UserBundle:UserNormal:newApiUser }
    
edit_normal_api_user:
    pattern: /edit/{id}
    defaults: { _controller: UserBundle:UserNormal:editApiUser }    
    
delete_normal_api_user:
    pattern: /delete/{id}
    defaults: { _controller: UserBundle:UserNormal:deleteApiUser }