projects:
    type: rest
    resource: "EasyScrumREST\\ProjectBundle\\Controller\\ProjectRestController"

backlogs:
    type: rest
    resource: "EasyScrumREST\\ProjectBundle\\Controller\\BacklogController"
    parent: projects
    