home:
    pattern:  /
    defaults: { _controller: FrontendBundle:Frontend:home }
    
calendar:
    pattern:  /calendar
    defaults: { _controller: FrontendBundle:Frontend:calendar }    
    
register:
    pattern:  /register
    defaults: { _controller: UserBundle:UserNormal:register }

statistics:
    pattern: /statistics/{project}
    defaults: { _controller: FrontendBundle:Frontend:statistics, project: null }
