parameters:
    synchronize.class: EasyScrumREST\SynchronizeBundle\Synchronize\Synchronize

services:
    synchronize:
        class: %synchronize.class%
        arguments: [@doctrine.orm.entity_manager]  
